### ISSUE TITLE
MorphemeDatabase still requires write permissions if the downloaded files already exist

### ISSUE THREAD

**Issue by JasonWeinzierl** [ecscstatsconsulting/morphemes#1]
## Expected Behavior

MorphemeDatabase should load the database if it exists on disk, without requiring write access.

## Actual Behavior

A `PermissionError` is raised when loading the existing database when the current process does not have write access.

## Steps to Reproduce the Problem

1. Download the db.json and MorphoLEX_en.xlsx files, save them as read-only or run the app in a security context without write access.
2. Call Morphemes.parse()
3. The following will be raised:

```
PermissionError: [Errno 13] Permission denied: 'db.json'

Traceback (most recent call last):
File "XXX.py", line XXX, in XXX
output = self.morphemes.parse(word)
File "/venv/lib/python3.8/site-packages/morphemes/__init__.py", line 10, in parse
morph_db_results = self.db.lookup(word)
File "/venv/lib/python3.8/site-packages/morphemes/utilities/morpheme_database/__init__.py", line 70, in lookup
db = self.load_db()
File "/venv/lib/python3.8/site-packages/morphemes/utilities/morpheme_database/__init__.py", line 42, in load_db
self.refresh()
File "/venv/lib/python3.8/site-packages/morphemes/utilities/morpheme_database/__init__.py", line 61, in refresh
db = self.create_db()
File "/venv/lib/python3.8/site-packages/morphemes/utilities/morpheme_database/__init__.py", line 36, in create_db
db = TinyDB(path)
File "/venv/lib/python3.8/site-packages/tinydb/database.py", line 94, in __init__
self._storage: Storage = storage(*args, **kwargs)
File "/venv/lib/python3.8/site-packages/tinydb/storages.py", line 102, in __init__
touch(path, create_dirs=create_dirs)
File "/venv/lib/python3.8/site-packages/tinydb/storages.py", line 31, in touch
with open(path, 'a'):
```

## Specifications

* Version: 1.0.9

## Temporary Solution

My temporary solution was to inherit from MorphemeDatabase and override `load_db`:

```
class MorphemeDatabaseWithAccessMode(MorphemeDatabase):
    def __init__(self, data_path: str, access_mode: str):
        self.access_mode = access_mode
        super().__init__(data_path=data_path)

    def load_db(self):
        path = self.get_db_path()
        if not os.path.exists(path):
            self.refresh()
        db = TinyDB(path, access_mode=self.access_mode)
        return db
```

This allows me to just pass in `r` instead of `r+` to TinyDB, which TinyDB passes to Storage via kwargs.

I'm relatively new to python, so there may be a better approach.

**Comment by paul0warren** [comment]
Greetings,
The latest release of this package now uses minimal permissions for the db json file.  It should now only open the db in "write" mode when performing the initial creation, normal lookup operations should all be done under "readonly" mode.  Sorry for the delay in getting this out.  Please let us know if this needs more work to fix your scenario, or if you notice anything else.  We really appreciate your feedback on this project!
Paul
